"use strict";

// functions/domain/companyContext.js — source unique du contexte entreprise (mise à jour : 2026-07).
// Fusion de DEUX sources : (1) les documents internes de cadrage (docs/DELTA_01_Veille_Strategique.md
// — autoritatifs : modèle économique, enjeux marge/sourcing, écosystème complet) et (2) l'audit
// web 2026-07 (identité publique, contexte partenaires 2026, concurrents confirmés, leviers
// réglementaires datés). Toute évolution du profil de l'entreprise se fait ICI et nulle part ailleurs.
const COMPANY_CONTEXT = `Neurones Technologies S.A. — intégrateur IT/Télécoms ivoirien (fondé 2010, siège Cocody II Plateaux Vallon, Abidjan ; 51-200 employés ; filiale à Ouagadougou, Burkina Faso), 15+ ans d'activité, 100+ projets complexes en Afrique de l'Ouest et du Centre (UEMOA/CEMAC).
BUSINESS UNITS : (1) ICT — intégration réseaux/télécoms (SD-WAN, fibre/5G), cybersécurité (démarche d'agrément PASSI), cloud (public/souverain), collaboration, datacenters, services managés (SOC/NOC, revenus récurrents), ERP (partenaire Odoo) ; (2) FORMATION — marque Neurones Academy (220+ formations certifiantes ; partenaires PECB, PMI, Microsoft, Cisco, CompTIA, EC-Council).
MODÈLE ÉCONOMIQUE & ENJEUX OPÉRATIONNELS (déterminants pour juger un signal) : marge brute faible sur le hardware (~7-21 %) → la valeur se fait sur les services, le managed et la formation ; forte dépendance aux DISTRIBUTEURS et à leurs LIGNES DE CRÉDIT (Hiperdist, Westcon-Comstor, Exclusive Networks — toute news pénurie/EOL/délais d'appro/conditions de crédit = alerte sourcing) ; cycle commande→facturation long (backlog à financer) ; concentration sur quelques grands comptes ; dépendance aux compétences rares (ingénieurs cyber/cloud — la veille talents/salaires compte) ; exposition FX (XOF arrimé EUR mais achats USD) et fiscalité douanière sur le matériel importé.
PARTENARIATS TECHNOLOGIQUES (30 partenaires suivis — éditeurs, constructeurs, distributeurs) : ÉDITEURS/CONSTRUCTEURS — (1) WALLIX niveau Premier (PAM, confirmé), (2) Cisco (réseau/sécurité/collaboration), (3) Fortinet (firewall/SD-WAN/SASE), (4) Palo Alto Networks (NGFW/SASE/XSIAM), (5) HPE/Aruba (serveurs/réseau/GreenLake), (6) Microsoft (M365/Azure/Security), (7) Odoo (ERP), (8) VMware/Broadcom (virtualisation), (9) Dell Technologies (serveurs/stockage), (10) Huawei (réseau/datacenter — aussi challenger concurrent), (11) Veeam (sauvegarde/DRP), (12) LogRhythm (SIEM), (13) Darktrace (NDR/IA), (14) Kaspersky (EDR/XDR, hub Abidjan), (15) Check Point (sécurité), (16) IBM (infra/QRadar/services), (17) Oracle (base de données/cloud), (18) Lenovo (postes/serveurs), (19) Nutanix (hyperconvergence — cible migrations VMware), (20) Sophos (endpoint/MDR), (21) Trend Micro (sécurité cloud/endpoint), (22) Schneider Electric/APC (énergie/onduleurs datacenter). DISTRIBUTEURS/CANAL : (23) Westcon-Comstor (Cisco/Palo Alto/Microsoft cloud Afrique), (24) Exclusive Networks (Fortinet exclusif Afrique de l'Ouest, Palo Alto), (25) Hiperdist (broadline local Abidjan), (26) HDF, (27) Ingram Micro, (28) TD SYNNEX (distribution HPE/Juniper mondiale), (29) Itancia, (30) AITEK/Polaris. Les changements de PROGRAMME PARTENAIRE (niveaux, rebates, certifications) et de LIGNES DE CRÉDIT distributeur impactent directement marges et statut.
CONTEXTE PARTENAIRE 2026 (critique) : refonte Cisco 360 (fin du statut Gold, bonus CPI expirant fin juillet 2026), refonte Palo Alto NextWave (fév. 2026, rebates liés à la platformisation), fusion HPE/Juniper Partner Ready Vantage (01/11/2026, distribution mondiale Ingram Micro/TD SYNNEX), exigences Microsoft Solutions Partner auditées (janv. 2026). EOO FortiGate série E + EOL Cisco Catalyst 3650 (oct. 2026) = pipelines de refresh chez les clients.
CLIENTS & COMPTES CIBLES (TOP 50 — références actuelles + prospects prioritaires CI/UEMOA) : RÉFÉRENCES ACTUELLES — (1) BCEAO, (2) BRVM, (3) BAD, (4) Orange Côte d'Ivoire, (5) SONAPIE, (6) SAFINE (Burkina). BANQUES & FINANCE UEMOA — (7) SGCI/Société Générale CI, (8) Ecobank CI, (9) Coris Bank, (10) NSIA Banque, (11) Bank of Africa (BOA), (12) Banque Atlantique, (13) BACI, (14) BNI (Banque Nationale d'Investissement), (15) BHCI, (16) Orabank, (17) Bridge Bank, (18) Afriland First Bank, (19) UBA CI, (20) Standard Chartered CI, (21) BOAD, (22) Trésor Public CI. ASSURANCES — (23) NSIA Assurances, (24) SUNU Assurances, (25) Sanlam/SAHAM, (26) Allianz CI, (27) Atlantique Assurances. TÉLÉCOMS & MONNAIE ÉLECTRONIQUE/FINTECH — (28) MTN CI, (29) Moov Africa CI, (30) Orange Money, (31) Wave, (32) fintechs/EME agréées. INSTITUTIONS, BAILLEURS & RÉGULATEURS — (33) Banque mondiale, (34) PAM, (35) Union Européenne (Délégation CI), (36) Commission UEMOA, (37) ARTCI, (38) ANSSI-CI, (39) AMF-UMOA. SECTEUR PUBLIC & ÉTAT (via SIGOMAP/DGMP) — (40) Ministère de la Transition Numérique, (41) DGI/Impôts, (42) Douanes CI, (43) CNPS, (44) CNAM, (45) Port Autonome d'Abidjan (PAA), (46) SODECI, (47) CIE, (48) PETROCI/SIR. GRANDS COMPTES PRIVÉS & INDUSTRIE — (49) SIFCA, (50) Africa Global Logistics (ex-Bolloré)/SITARAIL, plus Nestlé CI, CFAO, groupes miniers/agro-industriels. Financements structurants : Banque mondiale ~2 000 Mds FCFA de projets numériques CI (dont PADCI 152 M$), BAD/PARAE — la veille AO/financements est la source n°1 de pipeline régional.
CONCURRENTS DIRECTS (top 20 ESN/intégrateurs CI & UEMOA) : Talentys (le plus frontal — Fortinet+Wallix, SOC CNPS/CNAM), CBI (Cisco Gold, Abidjan/Dakar), Orange Business CI / OC2S (cloud souverain + cyber, créée 2025, 3 datacenters), SNDI (IT d'État, SIGFIP/SIGMAP), Inovatec (SOC 24/7, Fortinet/Palo Alto), SNEDAI Groupe (biométrie/cyber/datacenters), Groupe INOVA (concurrent BU Formation), SGCI (aussi cliente potentielle), New Digital Africa (ex-NSIA Technologies), Inetum CI, Atos, MTN Business CI, Cloudmania/Liquid C2 (CSP Microsoft), Sonatel CyberDefense (Sénégal), CIS (Computer Information Systems, intégrateur historique Abidjan), COMPUTEC (intégration/distribution IT), OSTEC (infrastructures & sécurité), COGITEC (services & infogérance IT), N'SOCITECH (intégration réseaux/IT), 3R (solutions IT/télécoms), INNOVATEC (intégrateur/services numériques), DATA PROTECT (cybersécurité & conformité — audits PCI DSS/ISO, acteur régional), TECHSO (services & solutions IT). Plus les pure players cloud/cyber et entrants low-cost. Menaces structurelles : désintermédiation (vente directe éditeurs, hyperscalers), Huawei (ESATIC, AO publics CI) ; Kaspersky fait d'Abidjan son hub Afrique de l'Ouest.
LEVIERS RÉGLEMENTAIRES MONÉTISABLES : audits SI triennaux obligatoires public+privé (décret 2021-917, agrément PASSI ANSSI-CI à viser), RGSSI (décret 2021-916, version 2025), instruction BCEAO 001-03-2021 (sécurité SI banques/paiements ; PI-SPI lancé sept. 2025), instructions AMF-UMOA mars 2024 sur les SI BRVM/DC-BR (upsell direct chez la BRVM cliente), loi 2013-450 données personnelles (étude nationale de conformité 2026), homologation ARTCI des équipements, souveraineté/localisation des données.
LENTILLE INNOVATION (élargie — NE PAS réduire la tech à « cloud + cybersécurité ») : l'innovation qui crée de la DEMANDE chez les clients de NT transforme d'abord leurs MÉTIERS, bien au-delà de l'infrastructure. À surveiller et à monétiser, par domaine d'application : (1) IA générative & agents métier (copilotes, scoring/octroi de crédit, détection de fraude, relation client, automatisation documentaire) ; (2) automatisation des processus (RPA/BPA, hyperautomation) ; (3) data & analytics/BI, gouvernance et plateformes de données ; (4) plateformes & API — open banking/finance embarquée, mobile money & fintech/EME, e-commerce & omnicanal ; (5) IoT & edge — industrie 4.0, logistique/traçabilité, énergie & smart grid, villes intelligentes ; (6) identité numérique, e-gov & GovTech ; (7) secteurs verticaux : insurtech, healthtech, agritech, edtech, retailtech, proptech. Le CLOUD et la CYBERSÉCURITÉ sont des ENABLERS transverses de ces transformations (souveraineté, conformité, résilience), pas la finalité. Pour chaque innovation sectorielle, le réflexe est : quel client/secteur est concerné → quelle offre NT (intégration, data/IA, sécurité, formation) l'accompagne.
GRILLE DE LECTURE D'UN SIGNAL (le « so-what » attendu) : EOL/pénurie/hausse chez un éditeur ou distributeur → alerte sourcing/lignes de crédit + opportunité de refresh chez les clients équipés ; AO/financement/budget chez un client ou bailleur → pipeline commercial (BU ICT ou FORMATION) ; nouvelle obligation réglementaire → offre d'audit/mise en conformité à pousser vers les comptes concernés ; innovation transformant un métier client (IA, data, fintech, IoT, e-gov…) → offre d'accompagnement/intégration à cadrer, sans se limiter au cloud/cyber ; mouvement concurrent (contrat gagné, partenariat éditeur, recrutement clé, implantation) → battlecard + riposte commerciale.
OBJECTIF COMMERCIAL : maximiser le pipeline d'affaires (objectif de signature ~12 Mds FCFA) sur CI/UEMOA.
ATTENTION HOMONYMIE : AUCUN lien avec le groupe français coté NEURONES (neurones.net, CA 810 M€), ni Neurones Technologies SA de Genève, ni Neurones IT Asia — tout signal concernant ces homonymes doit être ignoré ou marqué non pertinent.`;

module.exports = { COMPANY_CONTEXT };
