"use strict";

// functions/domain/companyContext.js — source unique du contexte entreprise (mise à jour : 2026-07)
const COMPANY_CONTEXT = `Neurones Technologies S.A. — intégrateur IT/Télécoms ivoirien (fondé 2010, siège Cocody II Plateaux Vallon, Abidjan ; 51-200 employés ; filiale à Ouagadougou, Burkina Faso), 15+ ans d'activité, 100+ projets complexes en Afrique de l'Ouest et du Centre.
BUSINESS UNITS : (1) ICT — intégration réseaux/télécoms, cybersécurité, cloud, collaboration, services managés, ERP (partenaire Odoo) ; (2) FORMATION — marque Neurones Academy (220+ formations certifiantes ; partenaires PECB, PMI, Microsoft, Cisco, CompTIA, EC-Council).
PARTENARIATS ÉDITEURS : WALLIX niveau Premier (PAM, confirmé), Cisco, Fortinet, Palo Alto Networks, HPE, Microsoft, Odoo. Distributeurs clés : Westcon-Comstor (Cisco/Palo Alto/Microsoft cloud Afrique), Exclusive Networks (Fortinet exclusif Afrique de l'Ouest, Palo Alto), Hiperdist (broadline local Abidjan).
CONTEXTE PARTENAIRE 2026 (critique) : refonte Cisco 360 (fin du statut Gold, bonus CPI expirant fin juillet 2026), refonte Palo Alto NextWave (fév. 2026, rebates liés à la platformisation), fusion HPE/Juniper Partner Ready Vantage (01/11/2026, distribution mondiale Ingram Micro/TD SYNNEX), exigences Microsoft Solutions Partner auditées (janv. 2026). EOO FortiGate série E + EOL Cisco Catalyst 3650 (oct. 2026) = pipelines de refresh chez les clients.
CLIENTS RÉFÉRENCES : BCEAO, BRVM, BAD, Orange Côte d'Ivoire, SONAPIE, SAFINE (Burkina). Cibles : banques/EME UEMOA, régulateurs, télécoms, secteur public ivoirien (AO via SIGOMAP), bailleurs (Banque mondiale ~2 000 Mds FCFA de projets numériques CI dont PADCI 152 M$, BAD/PARAE).
CONCURRENTS DIRECTS : Talentys (le plus frontal — Fortinet+Wallix, SOC CNPS/CNAM), CBI (Cisco Gold, Abidjan/Dakar), Orange Business CI / OC2S (cloud souverain + cyber, créée 2025, 3 datacenters), SNDI (IT d'État), SNEDAI, Inetum, Atos, Groupe INOVA (concurrent BU Formation), SGCI, Inovatec (SOC 24/7, Fortinet/Palo Alto), New Digital Africa (ex-NSIA Technologies), MTN Business, Cloudmania (CSP Microsoft), Sonatel CyberDefense (Sénégal). Menace montante : Huawei (ESATIC, AO publics CI) ; Kaspersky fait d'Abidjan son hub Afrique de l'Ouest.
LEVIERS RÉGLEMENTAIRES MONÉTISABLES : audits SI triennaux obligatoires public+privé (décret 2021-917, agrément PASSI ANSSI-CI à viser), RGSSI (décret 2021-916, version 2025), instruction BCEAO 001-03-2021 (sécurité SI banques/paiements ; PI-SPI lancé sept. 2025), instructions AMF-UMOA mars 2024 sur les SI BRVM/DC-BR (upsell direct chez la BRVM cliente), loi 2013-450 données personnelles (étude nationale de conformité 2026), homologation ARTCI des équipements.
OBJECTIF COMMERCIAL : maximiser le pipeline d'affaires (objectif de signature ~12 Mds FCFA) sur CI/UEMOA.
ATTENTION HOMONYMIE : AUCUN lien avec le groupe français coté NEURONES (neurones.net, CA 810 M€), ni Neurones Technologies SA de Genève, ni Neurones IT Asia — tout signal concernant ces homonymes doit être ignoré ou marqué non pertinent.`;

module.exports = { COMPANY_CONTEXT };
