"use strict";

// functions/domain/companyContext.js — source unique du contexte entreprise (mise à jour : 2026-07).
// Fusion de DEUX sources : (1) les documents internes de cadrage (docs/DELTA_01_Veille_Strategique.md
// — autoritatifs : modèle économique, enjeux marge/sourcing, écosystème complet) et (2) l'audit
// web 2026-07 (identité publique, contexte partenaires 2026, concurrents confirmés, leviers
// réglementaires datés). Toute évolution du profil de l'entreprise se fait ICI et nulle part ailleurs.
const COMPANY_CONTEXT = `Neurones Technologies S.A. — intégrateur IT/Télécoms ivoirien (fondé 2010, siège Cocody II Plateaux Vallon, Abidjan ; 51-200 employés ; filiale à Ouagadougou, Burkina Faso), 15+ ans d'activité, 100+ projets complexes en Afrique de l'Ouest et du Centre (UEMOA/CEMAC).
BUSINESS UNITS : (1) ICT — intégration réseaux/télécoms (SD-WAN, fibre/5G), cybersécurité (démarche d'agrément PASSI), cloud (public/souverain), collaboration, datacenters, services managés (SOC/NOC, revenus récurrents), ERP (partenaire Odoo) ; (2) FORMATION — marque Neurones Academy (220+ formations certifiantes ; partenaires PECB, PMI, Microsoft, Cisco, CompTIA, EC-Council).
MODÈLE ÉCONOMIQUE & ENJEUX OPÉRATIONNELS (déterminants pour juger un signal) : marge brute faible sur le hardware (~7-21 %) → la valeur se fait sur les services, le managed et la formation ; forte dépendance aux DISTRIBUTEURS et à leurs LIGNES DE CRÉDIT (Hiperdist, Westcon-Comstor, Exclusive Networks — toute news pénurie/EOL/délais d'appro/conditions de crédit = alerte sourcing) ; cycle commande→facturation long (backlog à financer) ; concentration sur quelques grands comptes ; dépendance aux compétences rares (ingénieurs cyber/cloud — la veille talents/salaires compte) ; exposition FX (XOF arrimé EUR mais achats USD) et fiscalité douanière sur le matériel importé.
PARTENARIATS ÉDITEURS/CONSTRUCTEURS : WALLIX niveau Premier (PAM, confirmé), Cisco, Fortinet, Palo Alto Networks, HPE/Aruba, Microsoft, Odoo ; écosystème élargi suivi : VMware/Broadcom, Dell, Huawei, Veeam, LogRhythm, Darktrace. Distributeurs : Westcon-Comstor (Cisco/Palo Alto/Microsoft cloud Afrique), Exclusive Networks (Fortinet exclusif Afrique de l'Ouest, Palo Alto), Hiperdist (broadline local Abidjan) ; autres acteurs canal régionaux : HDF, Ingram, Itancia, AITEK, Polaris. Les changements de PROGRAMME PARTENAIRE (niveaux, rebates, certifications) impactent directement marges et statut.
CONTEXTE PARTENAIRE 2026 (critique) : refonte Cisco 360 (fin du statut Gold, bonus CPI expirant fin juillet 2026), refonte Palo Alto NextWave (fév. 2026, rebates liés à la platformisation), fusion HPE/Juniper Partner Ready Vantage (01/11/2026, distribution mondiale Ingram Micro/TD SYNNEX), exigences Microsoft Solutions Partner auditées (janv. 2026). EOO FortiGate série E + EOL Cisco Catalyst 3650 (oct. 2026) = pipelines de refresh chez les clients.
CLIENTS RÉFÉRENCES : BCEAO, BRVM, BAD, Orange Côte d'Ivoire, SONAPIE, SAFINE (Burkina). Comptes/segments cibles : banques UEMOA (SGCI, Coris Bank, DIAMA…), EME/fintechs, télécoms (Orange, MTN, Moov), institutions & bailleurs (BAD, PAM, Banque mondiale, UE, État de CI), grands comptes privés ; secteur public via SIGOMAP. Financements structurants : Banque mondiale ~2 000 Mds FCFA de projets numériques CI (dont PADCI 152 M$), BAD/PARAE — la veille AO/financements est la source n°1 de pipeline régional.
CONCURRENTS DIRECTS : Talentys (le plus frontal — Fortinet+Wallix, SOC CNPS/CNAM), CBI (Cisco Gold, Abidjan/Dakar), Orange Business CI / OC2S (cloud souverain + cyber, créée 2025, 3 datacenters), SNDI (IT d'État), SNEDAI, Inetum, Atos, Groupe INOVA (concurrent BU Formation), SGCI (aussi cliente potentielle), Inovatec (SOC 24/7, Fortinet/Palo Alto), New Digital Africa (ex-NSIA Technologies), MTN Business, Cloudmania (CSP Microsoft), Sonatel CyberDefense (Sénégal), plus les pure players cloud/cyber et entrants low-cost. Menaces structurelles : désintermédiation (vente directe éditeurs, hyperscalers), Huawei (ESATIC, AO publics CI) ; Kaspersky fait d'Abidjan son hub Afrique de l'Ouest.
LEVIERS RÉGLEMENTAIRES MONÉTISABLES : audits SI triennaux obligatoires public+privé (décret 2021-917, agrément PASSI ANSSI-CI à viser), RGSSI (décret 2021-916, version 2025), instruction BCEAO 001-03-2021 (sécurité SI banques/paiements ; PI-SPI lancé sept. 2025), instructions AMF-UMOA mars 2024 sur les SI BRVM/DC-BR (upsell direct chez la BRVM cliente), loi 2013-450 données personnelles (étude nationale de conformité 2026), homologation ARTCI des équipements, souveraineté/localisation des données.
GRILLE DE LECTURE D'UN SIGNAL (le « so-what » attendu) : EOL/pénurie/hausse chez un éditeur ou distributeur → alerte sourcing/lignes de crédit + opportunité de refresh chez les clients équipés ; AO/financement/budget chez un client ou bailleur → pipeline commercial (BU ICT ou FORMATION) ; nouvelle obligation réglementaire → offre d'audit/mise en conformité à pousser vers les comptes concernés ; mouvement concurrent (contrat gagné, partenariat éditeur, recrutement clé, implantation) → battlecard + riposte commerciale.
OBJECTIF COMMERCIAL : maximiser le pipeline d'affaires (objectif de signature ~12 Mds FCFA) sur CI/UEMOA.
ATTENTION HOMONYMIE : AUCUN lien avec le groupe français coté NEURONES (neurones.net, CA 810 M€), ni Neurones Technologies SA de Genève, ni Neurones IT Asia — tout signal concernant ces homonymes doit être ignoré ou marqué non pertinent.`;

module.exports = { COMPANY_CONTEXT };
